### PR TITLE
Update wine to 9.8-wow64

### PR DESCRIPTION
**Pull request by pauleve**
Updates wine to 9.8-wow64 using Docker image from https://github.com/pauleve/docker-wine-wow64

```
./run-mtgo --update --test panard/mtgo:pr<#ID>
```

### CODE REVIEW

**Comment by dorianbrown** [comment]
This branch seems to solve a problem I had with emulating virtual desktops in the previous one, but now seems to introduce a new issue:

```
wine: Unhandled exception 0xe0434352 in thread 17c at address 00006FFFFFC23E67 (thread 017c), starting debugger...
01a8:err:system:find_monitor_from_path Failed to find monitor with path "DISPLAY\\DELA124\\0000&0000"
01a0:err:system:find_monitor_from_path Failed to find monitor with path "DISPLAY\\DELA124\\0000&0000"
01b4:err:system:find_monitor_from_path Failed to find monitor with path "DISPLAY\\DELA124\\0000&0000"
01b4:err:vulkan:vulkan_init Failed to load libvulkan.so.1
01b4:err:system:find_monitor_from_path Failed to find monitor with path "DISPLAY\\DELA124\\0000&0000"
====== MTGO.exe has started.
01c4:err:system:find_monitor_from_path Failed to find monitor with path "DISPLAY\\DELA124\\0000&0000"
01c4:err:vulkan:vulkan_init Failed to load libvulkan.so.1
01c4:err:system:find_monitor_from_path Failed to find monitor with path "DISPLAY\\DELA124\\0000&0000"
01d4:err:system:find_monitor_from_path Failed to find monitor with path "DISPLAY\\DELA124\\0000&0000"
01d4:err:vulkan:vulkan_init Failed to load libvulkan.so.1
01d4:err:system:find_monitor_from_path Failed to find monitor with path "DISPLAY\\DELA124\\0000&0000"
0050:err:system:find_monitor_from_path Failed to find monitor with path "DISPLAY\\DELA124\\0000&0000"
01a0:err:system:find_monitor_from_path Failed to find monitor with path "DISPLAY\\DELA124\\0000&0000"
01e4:err:system:find_monitor_from_path Failed to find monitor with path "DISPLAY\\DELA124\\0000&0000"
01e4:err:vulkan:vulkan_init Failed to load libvulkan.so.1
01e4:err:system:find_monitor_from_path Failed to find monitor with path "DISPLAY\\DELA124\\0000&0000"
0050:err:system:find_monitor_from_path Failed to find monitor with path "DISPLAY\\DELA124\\0000&0000"
01a0:err:system:find_monitor_from_path Failed to find monitor with path "DISPLAY\\DELA124\\0000&0000"
01a8:err:system:find_monitor_from_path Failed to find monitor with path "DISPLAY\\DELA124\\0000&0000"
01f4:err:system:find_monitor_from_path Failed to find monitor with path "DISPLAY\\DELA124\\0000&0000"
01f4:err:vulkan:vulkan_init Failed to load libvulkan.so.1
01f4:err:system:find_monitor_from_path Failed to find monitor with path "DISPLAY\\DELA124\\0000&0000"
0050:err:system:find_monitor_from_path Failed to find monitor with path "DISPLAY\\DELA124\\0000&0000"
01a0:err:system:find_monitor_from_path Failed to find monitor with path "DISPLAY\\DELA124\\0000&0000"
01a8:err:system:find_monitor_from_path Failed to find monitor with path "DISPLAY\\DELA124\\0000&0000"
01a0:err:dbghelp:pe_load_msc_debug_info -Debug info stripped, but no .DBG file in module L"kernelbase"
0208:err:system:find_monitor_from_path Failed to find monitor with path "DISPLAY\\DELA124\\0000&0000"
0208:err:vulkan:vulkan_init Failed to load libvulkan.so.1
0208:err:system:find_monitor_from_path Failed to find monitor with path "DISPLAY\\DELA124\\0000&0000"
====== shutting down
```

This only happens when using the `emulate virtual desktop` option in winecfg.

**Comment by pauleve** [comment]
Thanks for your feedback!
Vulkan-related messages are harmless.
Is it still working nevertheless, or is it crashing? If so, let's wait for 9.8, hopefully it will fix the monitor identification issue.

**Comment by dorianbrown** [comment]
This is what happens when I run this PR using an emulated virtual desktop:

image

Running without the virtual desktop starts normally, so seems specific to this version. Past PRs launched fine in a virtual desktop

**Comment by dorianbrown** [comment]
That seemed to fix it!

**Pull request merged**
